image: java:8

stages:
  - build
  - test
  - deploy
before_script:
  - chmod +x gradlew
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
build:
  stage: build
  script:
    - ./gradlew -g /cache/.gradle clean build
  allow_failure: false
test:
  stage: test
  script:
    - ./gradlew -g /cache/.gradle testApi
  allow_failure: false
deploy:
  stage: deploy
  only:
    - master
  script:
    - ./gradlew -g /cache/.gradle publish